 meta_product_name: "Better Place"
 meta_title: "Better Place - La rénovation en toute simplicité"
 meta_description: "Trouvez les experts pour mener à bien vos travaux de rénovation énergétique."
 meta_image: "imageog.png" # should exist in `app/assets/images/`
